# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
commit = last_git_commit
platform :ios do
  desc "Release the app via firebase app distribution"
  lane :distribute do
    firebase_app_distribution(
      app: "1:408505141940:ios:1d2339892d9ffd8cc325e1",
      groups: "internal, external",
      release_notes: commit[:message]
      # googleservice_info_plist_path: '../GoogleService-Info.plist'
    )
  end
end
