# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Firebase App Distribution"
  lane :distribute do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/
    vn = /versionName\s+"\d.\d.(\d+)"/
    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s
    s[vn, 1] = (versionCode+1).to_s
    f = File.new(path, 'w')
    f.write(s)
    f.close
    build_android_app(
      task: 'assemble',
      build_type: 'Release'
    )
    commit = last_git_commit
  end
end
