name: 🐛 Bug Report
description: Report a reproducible bug or regression in 100ms React Native Package
title: '🐛 '
labels: ['Needs Triage 🔍']
body:
  - type: markdown
    attributes:
      value: |
        Please provide all the information requested. Issues that do not follow this format are likely to stall.
        You can ask your questions on 100ms Discord as well: https://100ms.live/discord
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of what the bug is. Include screenshots if needed. Test using the [latest 100ms React Native release](https://github.com/100mslive/100ms-react-native/releases/latest) to make sure your issue has not already been fixed.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: 100ms React Native Version
      description: What is the latest version of 100ms React Native that this issue reproduces on? Please only list the highest version you tested.
      placeholder: ex. 1.7.0
    validations:
      required: true
  - type: input
    id: react-native-version
    attributes:
      label: React Native Version
      description: What is version React Native used?
      placeholder: ex. 0.67.0
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Please tell us exactly how to reproduce the problem you are running into. Do provide a detailed list of steps that reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected results
      description: What did you want to see?
      placeholder: |
        I expected to see...
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Code example, screenshot, or link to a repository
      description: |
        Please provide a minimal code example that reproduces the problem or a link to a repository on GitHub.
        You may provide a screenshot of the application if you think it is relevant to your bug report.
        Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

        Alternatively, you can use any editor
        which is capable of creating and running small React Native apps.
        Without this we will unlikely be able to progress on the issue, and because of that
        we regretfully will have to close it.
      value: |
        <details>
        <summary>Code sample</summary>

        <!--
              Please create a minimal reproducible sample that shows the problem
              and attach it below between the lines with the backticks.
        -->

        ```js
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: |
        Include the full logs of the commands you are running between the lines
        with the backticks below.
        If the logs are too large to be uploaded to Github, you may upload
        them as a `txt` file or use online tools like https://pastebin.com to
        share it.

        Note: Please do not upload screenshots of text. Instead, use code blocks
        or the above mentioned ways to upload logs.
      value: |
        <details>
        <summary>Logs</summary>

        ```console

        <!-- Paste your logs here -->

        ```

        </details>
