export enum HMSRoomUpdate {
  ROOM_MUTED = 'ROOM_MUTED',
  ROOM_UNMUTED = 'ROOM_UNMUTED',
  ROOM_TYPE_CHANGED = 'ROOM_TYPE_CHANGED',
  META_DATA_CHANGED = 'META_DATA_CHANGED',
  SERVER_RECORDING_STATE_UPDATED = 'SERVER_RECORDING_STATE_UPDATED',
  RTMP_STREAMING_STATE_UPDATED = 'RTMP_STREAMING_STATE_UPDATED',
  BROWSER_RECORDING_STATE_UPDATED = 'BROWSER_RECORDING_STATE_UPDATED',
  HLS_STREAMING_STATE_UPDATED = 'HLS_STREAMING_STATE_UPDATED',
  ROOM_ID_UPDATED = 'ROOM_ID_UPDATED',
}
