enum HMSUpdateListenerActions {
  ON_PREVIEW = 'ON_PREVIEW',
  ON_JOIN = 'ON_JOIN',
  ON_ROOM_UPDATE = 'ON_ROOM_UPDATE',
  ON_PEER_UPDATE = 'ON_PEER_UPDATE',
  ON_TRACK_UPDATE = 'ON_TRACK_UPDATE',
  ON_ERROR = 'ON_ERROR',
  ON_MESSAGE = 'ON_MESSAGE',
  ON_SPEAKER = 'ON_SPEAKER',
  RECONNECTING = 'RECONNECTING',
  RECONNECTED = 'RECONNECTED',
  ON_ROLE_CHANGE_REQUEST = 'ON_ROLE_CHANGE_REQUEST',
  ON_REMOVED_FROM_ROOM = 'ON_REMOVED_FROM_ROOM',
}

export default HMSUpdateListenerActions;
