/**
 * These are the available events emitted by the `HMSSDK`
 *
 * For more info about these events, checkout Event Listener docs
 * {@link https://www.100ms.live/docs/react-native/v2/how-to-guides/listen-to-room-updates/event-listeners}
 */
export enum HMSUpdateListenerActions {
  ON_PREVIEW = 'ON_PREVIEW',
  ON_JOIN = 'ON_JOIN',
  ON_ROOM_UPDATE = 'ON_ROOM_UPDATE',
  ON_PEER_UPDATE = '3',
  ON_TRACK_UPDATE = 'ON_TRACK_UPDATE',
  ON_ERROR = 'ON_ERROR',
  ON_MESSAGE = 'ON_MESSAGE',
  ON_SPEAKER = 'ON_SPEAKER',
  RECONNECTING = 'RECONNECTING',
  RECONNECTED = 'RECONNECTED',
  ON_ROLE_CHANGE_REQUEST = 'ON_ROLE_CHANGE_REQUEST',
  ON_CHANGE_TRACK_STATE_REQUEST = 'ON_CHANGE_TRACK_STATE_REQUEST',
  ON_REMOVED_FROM_ROOM = 'ON_REMOVED_FROM_ROOM',
  ON_RTC_STATS = 'ON_RTC_STATS',
  ON_LOCAL_AUDIO_STATS = 'ON_LOCAL_AUDIO_STATS',
  ON_LOCAL_VIDEO_STATS = 'ON_LOCAL_VIDEO_STATS',
  ON_REMOTE_AUDIO_STATS = 'ON_REMOTE_AUDIO_STATS',
  ON_REMOTE_VIDEO_STATS = 'ON_REMOTE_VIDEO_STATS',
  ON_AUDIO_DEVICE_CHANGED = 'ON_AUDIO_DEVICE_CHANGED',
  ON_SESSION_STORE_AVAILABLE = 'ON_SESSION_STORE_AVAILABLE',
  ON_SESSION_STORE_CHANGED = 'ON_SESSION_STORE_CHANGED',
}
