//
//  HMSManager.mm
//
//  TurboModule wrapper for the existing Swift `HMSManager` class.
//
//  Phase 1 / 1B of the New Architecture migration. This file adds
//  protocol conformance to the `NativeHMSManagerSpec` (Codegen-generated
//  from src/specs/NativeHMSManager.ts) WITHOUT modifying the Swift
//  source. Each forwarder adapts the protocol's named-label selectors
//  (e.g. `build:resolve:reject:`) to the existing Swift selectors with
//  positional underscore labels (e.g. `build:::`).
//
//  Why a category and not a separate class:
//    - The Swift HMSManager is registered as the RN module via
//      `RCT_EXTERN_MODULE` in HMSManager.m (under old arch) and remains
//      the lifecycle owner under new arch via `HMSManager.shared`.
//    - A category lets us add protocol conformance + `getTurboModule:`
//      to the existing class without creating a separate Obj-C class
//      that would conflict with the RN module-name registry or break
//      the singleton pattern from Phase 0.
//
//  Important caveats for the consumer-side first build:
//    - The `RNHmsSpec/RNHmsSpec.h` header below is generated by
//      Codegen at the consumer's `pod install` time. It does NOT
//      exist in the SDK source tree.
//    - The `react_native_hms-Swift.h` header is auto-generated by
//      the Swift compiler in the consumer's build. The exact name
//      depends on CocoaPods' module-name normalization; if your
//      build can't resolve it, check the CocoaPods-derived module
//      name (typically the package name with '-' → '_').
//    - Method-name collisions with the Swift class are intentional
//      — different Obj-C selectors (named labels vs positional) so
//      Obj-C dispatcher considers them distinct methods.
//

// Value-based check (not #ifdef): RN's Podfile + use_react_native! defines
// RCT_NEW_ARCH_ENABLED unconditionally as 0 or 1 depending on the build mode.
// `#ifdef` fires for both values; `#if` only when truthy.
#if RCT_NEW_ARCH_ENABLED

#import "RNHmsSpec/RNHmsSpec.h"
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>
// RCTViewManager / RCTUIManager must be imported BEFORE the Swift-generated
// header below — that header declares `@interface HMSHLSPlayerManager :
// RCTViewManager` and properties of type `RCTDirectEventBlock` without
// importing React itself. Under static-library mode these types are visible
// via shared header search paths; under `use_frameworks! :linkage => :static`
// (Expo SDK 54+), our `.mm` files compile inside the react_native_hms
// framework and don't see React's types unless we import them explicitly here.
#import <React/RCTViewManager.h>
#import <React/RCTUIManager.h>

// Auto-generated by `swiftc -emit-objc-header`. Two import paths cover both
// pod linkage modes:
//   - Static framework (`use_frameworks! :linkage => :static`, the default
//     in Expo SDK 54+): swiftc writes the header into the framework's
//     `Headers/` directory, reachable only via the framework module map
//     (angle-bracket form).
//   - Static library (vanilla RN default): Xcode emits the header into the
//     pod's `DerivedSources/` directory, which CocoaPods adds to
//     `USER_HEADER_SEARCH_PATHS`. Only the quoted form resolves there.
// `__has_include` picks whichever path exists for the consumer's setup.
#if __has_include(<react_native_hms/react_native_hms-Swift.h>)
#import <react_native_hms/react_native_hms-Swift.h>
#else
#import "react_native_hms-Swift.h"
#endif

@interface HMSManager (TurboModuleConformance) <NativeHMSManagerSpec>
@end

@implementation HMSManager (TurboModuleConformance)

#pragma mark - TurboModule registration

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params {
  return std::make_shared<facebook::react::NativeHMSManagerSpecJSI>(params);
}

#pragma mark - Promise method forwarders
//
// The Codegen-generated `NativeHMSManagerSpec` protocol declares each
// async method with named labels: `methodName:resolve:reject:`. The
// existing Swift HMSManager exposes them with positional underscore
// labels (selector: `methodName:::`). The macro below adapts the
// protocol's expected selector to the existing Swift selector by
// dispatching through `[self methodName:data :resolve :reject]`.
//
// `self` here refers to the same HMSManager instance — the category's
// method has a different selector from the Swift method (named labels
// vs positional), so this is NOT infinite recursion.
//

#define FORWARD_PROMISE(name)                                        \
  -(void)name : (NSDictionary *)data                                 \
            resolve : (RCTPromiseResolveBlock)resolve                \
                reject : (RCTPromiseRejectBlock)reject {             \
    [self name:data :resolve :reject];                               \
  }

// Lifecycle
FORWARD_PROMISE(build)
FORWARD_PROMISE(destroy)
FORWARD_PROMISE(previewForRole)
FORWARD_PROMISE(cancelPreview)
FORWARD_PROMISE(leave)
FORWARD_PROMISE(endRoom)

// Track operations
// `setLocalMute` / `setLocalVideoMute` are declared as `void` in the TS spec
// (fire-and-forget — the Swift impl is sync). The protocol expects a 1-arg
// selector but the existing Swift method has 3 positional args (data, resolve,
// reject). Forward 1-arg → 3-arg with nil resolve/reject so the Swift impl
// still runs and any rejection is silently dropped (matching `void` semantics).
- (void)setLocalMute:(NSDictionary *)data {
  [self setLocalMute:data :nil :nil];
}
- (void)setLocalVideoMute:(NSDictionary *)data {
  [self setLocalVideoMute:data :nil :nil];
}
FORWARD_PROMISE(isMute)
FORWARD_PROMISE(changeTrackState)
FORWARD_PROMISE(changeTrackStateForRoles)
FORWARD_PROMISE(setVolume)
FORWARD_PROMISE(remoteMuteAllAudio)
FORWARD_PROMISE(setPlaybackAllowed)
FORWARD_PROMISE(isPlaybackAllowed)
FORWARD_PROMISE(setPlaybackForAllAudio)
FORWARD_PROMISE(getRemoteVideoTrackFromTrackId)
FORWARD_PROMISE(getRemoteAudioTrackFromTrackId)
FORWARD_PROMISE(getVideoTrackLayer)
FORWARD_PROMISE(getVideoTrackLayerDefinition)
FORWARD_PROMISE(setVideoTrackLayer)
FORWARD_PROMISE(captureImageAtMaxSupportedResolution)

// Peer operations
FORWARD_PROMISE(getLocalPeer)
FORWARD_PROMISE(getRemotePeers)
FORWARD_PROMISE(getRoles)
FORWARD_PROMISE(getRoom)
FORWARD_PROMISE(changeName)
FORWARD_PROMISE(changeMetadata)
FORWARD_PROMISE(changeRole)
FORWARD_PROMISE(changeRoleOfPeer)
FORWARD_PROMISE(changeRoleOfPeersWithRoles)
FORWARD_PROMISE(acceptRoleChange)
FORWARD_PROMISE(removePeer)
FORWARD_PROMISE(raiseLocalPeerHand)
FORWARD_PROMISE(lowerLocalPeerHand)
FORWARD_PROMISE(lowerRemotePeerHand)

// Peer list iterator (the sync `getPeerListIterator` is below)
FORWARD_PROMISE(peerListIteratorHasNext)
FORWARD_PROMISE(peerListIteratorNext)

// Messaging
FORWARD_PROMISE(sendBroadcastMessage)
FORWARD_PROMISE(sendGroupMessage)
FORWARD_PROMISE(sendDirectMessage)

// RTMP / Recording / HLS streaming
FORWARD_PROMISE(startRTMPOrRecording)
FORWARD_PROMISE(stopRtmpAndRecording)
FORWARD_PROMISE(startHLSStreaming)
FORWARD_PROMISE(stopHLSStreaming)
FORWARD_PROMISE(sendHLSTimedMetadata)

// Screen share
FORWARD_PROMISE(startScreenshare)
FORWARD_PROMISE(stopScreenshare)
FORWARD_PROMISE(isScreenShared)

// Audio share — iOS API
FORWARD_PROMISE(playAudioShare)
FORWARD_PROMISE(pauseAudioShare)
FORWARD_PROMISE(resumeAudioShare)
FORWARD_PROMISE(stopAudioShare)
FORWARD_PROMISE(setAudioShareVolume)
FORWARD_PROMISE(audioShareCurrentTime)
FORWARD_PROMISE(audioShareDuration)
FORWARD_PROMISE(audioShareIsPlaying)

// Audio output
FORWARD_PROMISE(switchAudioOutput)
FORWARD_PROMISE(switchAudioOutputUsingIOSUI)

// PiP (iOS-implemented)
// Note: `setupPIP` is declared in the TS spec and the legacy paper bridge
// (`RCT_EXTERN_METHOD` in HMSManager.m) but the Swift class never implemented
// it. Under old arch this would have crashed at runtime if called; no JS
// caller currently does. Stubbed below — not via FORWARD_PROMISE.
FORWARD_PROMISE(stopPIP)
FORWARD_PROMISE(disposePIP)
FORWARD_PROMISE(isPIPActive)
FORWARD_PROMISE(changeIOSPIPVideoTrack)
FORWARD_PROMISE(setActiveSpeakerInIOSPIP)

// Session store / metadata
FORWARD_PROMISE(getSessionMetadataForKey)
FORWARD_PROMISE(setSessionMetadataForKey)
FORWARD_PROMISE(addKeyChangeListener)
FORWARD_PROMISE(removeKeyChangeListener)

// Polls / Quiz
FORWARD_PROMISE(quickStartPoll)
FORWARD_PROMISE(addResponseOnPollQuestion)
FORWARD_PROMISE(stopPoll)
FORWARD_PROMISE(fetchLeaderboard)

// Whiteboard
FORWARD_PROMISE(startWhiteboard)
FORWARD_PROMISE(stopWhiteboard)

// Transcripts
FORWARD_PROMISE(handleRealTimeTranscription)

// Noise cancellation
FORWARD_PROMISE(enableNoiseCancellationPlugin)
FORWARD_PROMISE(disableNoiseCancellationPlugin)
FORWARD_PROMISE(isNoiseCancellationPluginEnabled)
FORWARD_PROMISE(isNoiseCancellationPluginAvailable)

// Video plugin (iOS only)
FORWARD_PROMISE(enableVideoPlugin)
FORWARD_PROMISE(disableVideoPlugin)
FORWARD_PROMISE(changeVirtualBackground)
FORWARD_PROMISE(setVideoFilterParameter)

// Misc / system / config
FORWARD_PROMISE(enableEvent)
FORWARD_PROMISE(disableEvent)
FORWARD_PROMISE(restrictData)
FORWARD_PROMISE(getAuthTokenByRoomCode)
FORWARD_PROMISE(getRoomLayout)
FORWARD_PROMISE(setAlwaysScreenOn)

#undef FORWARD_PROMISE

#pragma mark - Multi-arg method forwarder

// `handlePipActions` is the only iOS method with two non-promise args
// (action: string, data: Object). The Swift selector is
// `handlePipActions::::` (4 colons, all positional).
- (void)handlePipActions:(NSString *)action
                    data:(NSDictionary *)data
                 resolve:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject {
  [self handlePipActions:action :data :resolve :reject];
}

#pragma mark - Unimplemented iOS methods

// Declared in TS spec but never implemented in Swift. Reject gracefully so
// JS callers get an error rather than a crash. See note at FORWARD_PROMISE
// block above.
- (void)setupPIP:(NSDictionary *)data
         resolve:(RCTPromiseResolveBlock)resolve
          reject:(RCTPromiseRejectBlock)reject {
  reject(@"HMS_PLATFORM_UNSUPPORTED", @"setupPIP is not implemented on iOS", nil);
}

#pragma mark - Methods with matching selectors (no forwarder needed)
//
// The following methods have selectors that already match between the
// Codegen protocol and the existing Swift class — same arity, same
// labels — so the protocol's required method is satisfied by the
// existing Swift implementation directly. NO forwarder is needed:
//
//   Sync methods (return value, no resolve/reject):
//     - getPeerProperty:           [Swift selector matches protocol]
//     - getRoomProperty:           [Swift selector matches protocol]
//     - getPeerListIterator:       [Swift selector matches protocol]
//
//   Void methods (single dictionary param, no resolve/reject):
//     - preview:           (Swift exposes preview:)
//     - join:              (Swift exposes join:)
//     - switchCamera:      (Swift exposes switchCamera:)
//     - enableNetworkQualityUpdates:
//     - disableNetworkQualityUpdates:
//

#pragma mark - Android-only methods (stubs)
//
// These methods are declared in the cross-platform spec but are not
// implemented on iOS. Calls from JS without a `Platform.OS === 'android'`
// guard will reject with a 'HMS_PLATFORM_UNSUPPORTED' error.

- (void)checkNotifications:(RCTPromiseResolveBlock)resolve
                    reject:(RCTPromiseRejectBlock)reject {
  reject(@"HMS_PLATFORM_UNSUPPORTED", @"checkNotifications is Android-only", nil);
}

- (void)getAudioDevicesList:(NSDictionary *)data
                    resolve:(RCTPromiseResolveBlock)resolve
                     reject:(RCTPromiseRejectBlock)reject {
  reject(@"HMS_PLATFORM_UNSUPPORTED", @"getAudioDevicesList is Android-only", nil);
}

- (void)getAudioOutputRouteType:(NSDictionary *)data
                        resolve:(RCTPromiseResolveBlock)resolve
                         reject:(RCTPromiseRejectBlock)reject {
  reject(@"HMS_PLATFORM_UNSUPPORTED", @"getAudioOutputRouteType is Android-only", nil);
}

- (void)setAudioMode:(NSDictionary *)data
             resolve:(RCTPromiseResolveBlock)resolve
              reject:(RCTPromiseRejectBlock)reject {
  reject(@"HMS_PLATFORM_UNSUPPORTED", @"setAudioMode is Android-only", nil);
}

- (void)setAudioMixingMode:(NSDictionary *)data
                   resolve:(RCTPromiseResolveBlock)resolve
                    reject:(RCTPromiseRejectBlock)reject {
  reject(@"HMS_PLATFORM_UNSUPPORTED", @"setAudioMixingMode is Android-only", nil);
}

- (void)getAudioMixingMode:(NSDictionary *)data
                   resolve:(RCTPromiseResolveBlock)resolve
                    reject:(RCTPromiseRejectBlock)reject {
  reject(@"HMS_PLATFORM_UNSUPPORTED", @"getAudioMixingMode is Android-only", nil);
}

- (void)getVolume:(NSDictionary *)data
          resolve:(RCTPromiseResolveBlock)resolve
           reject:(RCTPromiseRejectBlock)reject {
  reject(@"HMS_PLATFORM_UNSUPPORTED", @"getVolume is Android-only", nil);
}

- (void)setPermissionsAccepted:(NSDictionary *)data
                       resolve:(RCTPromiseResolveBlock)resolve
                        reject:(RCTPromiseRejectBlock)reject {
  reject(@"HMS_PLATFORM_UNSUPPORTED", @"setPermissionsAccepted is Android-only", nil);
}

- (void)startAudioshare:(NSDictionary *)data
                resolve:(RCTPromiseResolveBlock)resolve
                 reject:(RCTPromiseRejectBlock)reject {
  reject(@"HMS_PLATFORM_UNSUPPORTED", @"startAudioshare is Android-only", nil);
}

- (void)stopAudioshare:(NSDictionary *)data
               resolve:(RCTPromiseResolveBlock)resolve
                reject:(RCTPromiseRejectBlock)reject {
  reject(@"HMS_PLATFORM_UNSUPPORTED", @"stopAudioshare is Android-only", nil);
}

- (void)isAudioShared:(NSDictionary *)data
              resolve:(RCTPromiseResolveBlock)resolve
               reject:(RCTPromiseRejectBlock)reject {
  reject(@"HMS_PLATFORM_UNSUPPORTED", @"isAudioShared is Android-only", nil);
}

#pragma mark - Android-only void methods (no-op stubs)

- (void)setAudioDeviceChangeListener:(NSDictionary *)data {
  // No-op on iOS — Android-only
}

- (void)hideSystemBars {
  // No-op on iOS — Android-only
}

- (void)showSystemBars {
  // No-op on iOS — Android-only
}

#pragma mark - Android-only sync methods (stubs)

- (NSNumber *)setSoftInputMode:(double)inputMode {
  // No-op on iOS — Android-only — returns 0
  return @(0);
}

- (NSNumber *)getSoftInputMode {
  // No-op on iOS — Android-only — returns 0
  return @(0);
}

@end

#endif  // RCT_NEW_ARCH_ENABLED
