//
//  HMSViewComponentView.mm
//
//  Fabric component view for `<HMSView />` — the native video tile.
//
//  Phase 1 / 1B group 2 of the New Architecture migration. This file
//  implements the Fabric counterpart to the existing paper-side
//  `HMSView` (RCTViewManager) + `HmssdkDisplayView` (UIView subclass).
//
//  Architecture overview:
//    - Under New Architecture, RN renders native views via Fabric.
//    - Fabric expects a class that subclasses `RCTViewComponentView`,
//      conforms to a generated protocol (e.g. `RCTHMSViewViewProtocol`),
//      and overrides `updateProps:`, `handleCommand:args:`, etc.
//    - The actual UI (camera surface) is still the existing Swift
//      `HmssdkDisplayView` — we host it inside this Fabric wrapper as
//      a sub-view, forwarding props and commands to it.
//
//  Event-emission pattern (Pattern A — block-prop interception):
//    - `HmssdkDisplayView` already has `@objc var onDataReturned:
//      RCTDirectEventBlock?` (the legacy paper event mechanism).
//    - In `initWithFrame:`, we set that block to a translator block
//      that converts the NSDictionary payload from Swift into the
//      typed C++ struct expected by the Fabric event emitter.
//    - This means Swift code is UNCHANGED — it still calls its block
//      prop the same way it always has. The .mm wrapper intercepts.
//    - Industry standard for migrating Swift-based RN libraries to
//      Fabric without rewriting Swift code.
//
//  Important caveats for the consumer-side first build:
//    - The `react/renderer/components/RNHmsSpec/...` headers below are
//      generated by Codegen at the consumer's `pod install` time. They
//      do NOT exist in the SDK source tree.
//    - The `react_native_hms-Swift.h` header is auto-generated by the
//      Swift compiler in the consumer's build. The exact name depends
//      on CocoaPods' module-name normalization.
//    - `HMSViewCls()` at the bottom is the public C function that the
//      Fabric component-views plugin registry calls to register this
//      class.
//

#ifdef RCT_NEW_ARCH_ENABLED

#import <React/RCTViewComponentView.h>
#import <React/RCTConversions.h>

#import <react/renderer/components/RNHmsSpec/ComponentDescriptors.h>
#import <react/renderer/components/RNHmsSpec/EventEmitters.h>
#import <react/renderer/components/RNHmsSpec/Props.h>
#import <react/renderer/components/RNHmsSpec/RCTComponentViewHelpers.h>

#import "RCTFabricComponentsPlugins.h"

// Pulled in before the Swift-generated header so every type the auto-generated
// `-Swift.h` references is visible at parse time. The Swift header declares
// every @objc-exposed class — including `HMSManager : RCTEventEmitter` and
// `HMSHLSPlayerManager : RCTViewManager` — so this .mm must see those base
// classes even though it doesn't use them directly. Under static-library mode
// they're visible via shared header search paths; under
// `use_frameworks! :linkage => :static` (Expo SDK 54+) we need explicit imports.
// See HMSManager.mm for the full explanation.
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>
#import <React/RCTViewManager.h>
#import <React/RCTUIManager.h>

// Auto-generated Swift bridging header. Two import paths cover both pod
// linkage modes — see HMSManager.mm for the full explanation.
#if __has_include(<react_native_hms/react_native_hms-Swift.h>)
#import <react_native_hms/react_native_hms-Swift.h>
#else
#import "react_native_hms-Swift.h"
#endif

using namespace facebook::react;

@interface HMSViewComponentView : RCTViewComponentView <RCTHMSViewViewProtocol>
@end

@implementation HMSViewComponentView {
  // The Swift UIView that does the actual video rendering. Owned and
  // hosted as our `contentView`.
  HmssdkDisplayView *_view;
}

#pragma mark - Component descriptor registration

// Tells Fabric which generated component descriptor maps to this class.
// `HMSViewComponentDescriptor` is generated by Codegen from the TS spec
// `src/specs/HMSViewNativeComponent.ts`.
+ (ComponentDescriptorProvider)componentDescriptorProvider {
  return concreteComponentDescriptorProvider<HMSViewComponentDescriptor>();
}

#pragma mark - View lifecycle

- (instancetype)initWithFrame:(CGRect)frame {
  if (self = [super initWithFrame:frame]) {
    // Initialize default props from the generated `HMSViewProps` struct.
    static const auto defaultProps = std::make_shared<const HMSViewProps>();
    _props = defaultProps;

    // Instantiate the Swift view directly. `HmssdkDisplayView.hmsCollection`
    // is now a *computed* property that reads live from `HMSManager.shared`
    // on every access, so no explicit wiring is needed — the lookup
    // automatically reflects the currently-active HMS instance even after
    // leave → rejoin cycles.
    _view = [[HmssdkDisplayView alloc] init];
    self.contentView = _view;

    // ─────────────────────────────────────────────────────────────────
    // Pattern A — block-prop interception for event emission.
    //
    // `HmssdkDisplayView` exposes `@objc var onDataReturned:
    // RCTDirectEventBlock?` (the legacy paper event mechanism). Under
    // Fabric, events flow through a typed C++ event emitter held in
    // `_eventEmitter` (set by Fabric via `updateEventEmitter:`).
    //
    // The block below bridges the two: when the Swift view calls
    // `onDataReturned([...])`, this translator converts the dictionary
    // into the generated `OnDataReturned` C++ struct and dispatches
    // through the Fabric event emitter.
    //
    // This pattern requires NO Swift changes and works transparently
    // alongside the legacy paper code path (which sets the block
    // through the old `RCTDirectEventBlock` view-manager mechanism).
    // ─────────────────────────────────────────────────────────────────
    __weak __typeof(self) weakSelf = self;
    _view.onDataReturned = ^(NSDictionary *body) {
      __strong __typeof(weakSelf) strongSelf = weakSelf;
      if (!strongSelf || !strongSelf->_eventEmitter) {
        return;
      }
      // Cast the type-erased _eventEmitter to our component's typed
      // event emitter (generated by Codegen).
      auto emitter = std::dynamic_pointer_cast<HMSViewEventEmitter const>(
          strongSelf->_eventEmitter);
      if (!emitter) {
        return;
      }
      // Convert NSDictionary payload → typed C++ struct.
      // The shape matches `OnDataReturnedPayload` from
      // src/specs/HMSViewNativeComponent.ts.
      HMSViewEventEmitter::OnDataReturned event = {};
      if (body[@"requestId"]) {
        event.requestId = [body[@"requestId"] intValue];
      }
      if ([body[@"result"] isKindOfClass:[NSString class]]) {
        event.result = [body[@"result"] UTF8String];
      } else if ([body[@"error"] isKindOfClass:[NSArray class]] &&
                 [(NSArray *)body[@"error"] count] >= 2) {
        // Swift sends error as ["6001", "message"] tuple; flatten to
        // a string for the Fabric payload.
        NSString *errMessage =
            [(NSArray *)body[@"error"] componentsJoinedByString:@": "];
        event.error = [errMessage UTF8String];
      }
      emitter->onDataReturned(event);
    };

    // Note: `onChange` (resolution-change event) is not wired here.
    // The Swift `HmssdkDisplayView` does not currently fire a
    // resolution-change callback on iOS — the equivalent
    // `topChange`/`onChange` event is an Android-only behavior in the
    // existing SDK (see `HMSSDKViewManager.kt`). If iOS gains this
    // event in the future, add a second block-intercept here.
  }
  return self;
}

#pragma mark - Prop dispatch
//
// Called by Fabric whenever any prop changes. We diff old vs new and
// forward each changed prop to the Swift view. This is the Fabric
// equivalent of the paper view manager's `setX:forView:` setters.

- (void)updateProps:(Props::Shared const &)props
           oldProps:(Props::Shared const &)oldProps {
  const auto &oldViewProps =
      *std::static_pointer_cast<HMSViewProps const>(_props);
  const auto &newViewProps = *std::static_pointer_cast<HMSViewProps const>(props);

  // scaleType (string)
  if (oldViewProps.scaleType != newViewProps.scaleType) {
    _view.scaleType = RCTNSStringFromString(newViewProps.scaleType);
  }

  // autoSimulcast (bool)
  if (oldViewProps.autoSimulcast != newViewProps.autoSimulcast) {
    _view.autoSimulcast = newViewProps.autoSimulcast;
  }

  // setZOrderMediaOverlay is Android-only — Swift HmssdkDisplayView
  // does not implement it on iOS. Silently ignore changes.

  // data (struct of trackId, id, mirror, scaleType)
  // Swift expects an NSDictionary, so reconstruct one and assign it on
  // every updateProps call — NOT only when the struct values differ.
  //
  // Why: HmssdkDisplayView.data is a `didSet` setter that, among other
  // things, looks up the HMSVideoTrack by trackId in the active room.
  // For remote peers, the track isn't in the room at first mount —
  // it arrives later via SDK peer/track update events. Paper called
  // setData: on every render, so the lookup retried until the track
  // appeared; an equality-based optimization here would re-create the
  // bug where remote video never appears even though the same trackId
  // becomes valid on a later render.
  const auto &newData = newViewProps.data;
  _view.data = @{
    @"trackId" : RCTNSStringFromString(newData.trackId),
    @"id" : RCTNSStringFromString(newData.id),
    @"mirror" : @(newData.mirror),
    @"scaleType" : RCTNSStringFromString(newData.scaleType),
  };

  [super updateProps:props oldProps:oldProps];
}

#pragma mark - Imperative commands

// Generic command dispatcher. The `RCTHMSViewHandleCommand` helper is
// generated by Codegen and dispatches to `capture:` below based on the
// command name from the JS spec.
- (void)handleCommand:(NSString const *)commandName args:(NSArray const *)args {
  RCTHMSViewHandleCommand(self, commandName, args);
}

// Implementation of the `capture` imperative command from the spec.
// Dispatched here by `RCTHMSViewHandleCommand` when JS calls
// `Commands.capture(viewRef, requestId)`.
- (void)capture:(NSInteger)requestId {
  [_view captureHmsView:@(requestId)];
}

@end

#pragma mark - Plugin registration

// Public C function that the Fabric component-views plugin registry
// calls (via RCTFabricComponentsPlugins) to register this class as
// the implementation of `<HMSView />`.
Class<RCTComponentViewProtocol> HMSViewCls(void) {
  return HMSViewComponentView.class;
}

#endif  // RCT_NEW_ARCH_ENABLED
