const RESET_JOIN_CONFIG = 'RESET_JOIN_CONFIG';

const CHANGE_DEBUG_INFO = 'CHANGE_DEBUG_INFO';

const CHANGE_JOIN_AUDIO_MUTED = 'CHANGE_JOIN_AUDIO_MUTED';

const CHANGE_JOIN_VIDEO_MUTED = 'CHANGE_JOIN_VIDEO_MUTED';

const CHANGE_MIRROR_CAMERA = 'CHANGE_MIRROR_CAMERA';

const CHANGE_JOIN_SKIP_PREVIEW = 'CHANGE_JOIN_SKIP_PREVIEW';

const CHANGE_AUDIO_MIXER = 'CHANGE_AUDIO_MIXER';

const CHANGE_MUSIC_MODE = 'CHANGE_MUSIC_MODE';

const CHANGE_SOFTWARE_DECODER = 'CHANGE_SOFTWARE_DECODER';

const CHANGE_AUTO_RESIZE = 'CHANGE_AUTO_RESIZE';

const CHANGE_AUTO_SIMULCAST = 'CHANGE_AUTO_SIMULCAST';

const CHANGE_USE_STATIC_USERID = 'CHANGE_USE_STATIC_USERID';

export default {
  RESET_JOIN_CONFIG,
  CHANGE_DEBUG_INFO,
  CHANGE_JOIN_AUDIO_MUTED,
  CHANGE_JOIN_VIDEO_MUTED,
  CHANGE_MIRROR_CAMERA,
  CHANGE_JOIN_SKIP_PREVIEW,
  CHANGE_AUDIO_MIXER,
  CHANGE_MUSIC_MODE,
  CHANGE_SOFTWARE_DECODER,
  CHANGE_AUTO_RESIZE,
  CHANGE_AUTO_SIMULCAST,
  CHANGE_USE_STATIC_USERID,
};
