name: Pull Request
on: [pull_request, workflow_dispatch]
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  trunk_check:
    name: Trunk Check Runner
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - run: |
      #     curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.44.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      # - name: Run ktlint
      #   run: |
      #     ktlint --reporter=checkstyle,output=build/ktlint-report.xml
      #   continue-on-error: true
      # - uses: yutailang0119/action-ktlint@v3
      #   with:
      #     report-path: build/*.xml
      #   continue-on-error: false

      # - name: Trunk Check
      #   uses: trunk-io/trunk-action@v1
      #   with:
      #     post-annotations: true

      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
