name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
      - develop
    paths-ignore:
      - "**.md"
      - doc/**
      - .git/
      - .vscode/
      - "**.txt"

jobs:

  release_android:
    name: Release Android App on Firebase
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11.x
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.0.0
      - name: Setup Fastlane
        env:
          REACT_NATIVE_HMS_JSON: ${{ secrets.REACT_NATIVE_HMS_JSON }}
          IOS_APPFILE: ${{ secrets.IOS_APPFILE }}
          IOS_FASTFILE: ${{ secrets.IOS_FASTFILE }}
          IOS_PLUGINFILE: ${{ secrets.IOS_PLUGINFILE }}
        run: |
          cd packages/react-native-room-kit/example/android

          echo $REACT_NATIVE_HMS_JSON > reactnative-hms-a32ef61302c5.json

          cd fastlane

          pwd
          ls -la

          cd ../../ios
          echo $REACT_NATIVE_HMS_JSON > reactnative-hms-a32ef61302c5.json

          pwd
          mkdir fastlane
          cd fastlane
          echo $IOS_APPFILE > Appfile
          echo $IOS_FASTFILE > Fastfile
          echo $IOS_PLUGINFILE > Pluginfile
          pwd
          ls -la
      - name: Run Release Script
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          SLACK_URL: ${{ secrets.SLACK_URL }}
        run: sh release-apps.sh
